### ISSUE TITLE
Can this be used with the new SSO version 2 of bluemix?

### ISSUE THREAD

**Issue by nacho4d** [osipov/passport-ibmid-oauth2#3]
I wonder if this module works with the new SingleSignOn version in Bluemix?

https://www.ng.bluemix.net/docs/#services/SingleSignOn/index.html#sso_gettingstarted
> Note: This documentation replaces the documentation for previous versions of the Single Sign On service. If you used the service before December 29, 2014, see IBM Single Sign On for Bluemix Version 1.0 documentation.

The new documentation does not mention any way how to implement SSO within a native app (the old used to!) so I was wondering if it possible to do this with this module?

I guess my server should send a challenge with an authorization url the native mobile app should should in the browser, after sso it should go back to the native app. the problem is where do I get this url from?
I was trying `passport-idaas-openidconnect` (which is module mentioned in this new documentation) but so far I don't know how to make it work with a native app.

**Comment by osipov** [comment]
@nacho4d apologies for a very late answer. As of today, this package does work with the latest version of SSO. However, should you choose to use it, please be aware of the following warning from the IDaaS team.

This IDaaS v1 service is being temporarily re-enabled to facilitate IBM web identity authentication. Any users of this facility must recognise that it is being made available on a temporary basis, and should be ready to migrate to IDaaS v2 or another service when this feature is made available on that service. This service will only provide authentication against IBM's IBM web identity, the authentication credential intended for use by IBM customers and partners on IBM external applications. Any Bluemix application intended for business use, e.g. access by IBM employees or contractors and containing IBM data, must use IBM w3ID (intranet ID and password). This must be enabled through the IDaaS v2 service enterprise federation functionality for w3ID.
There is no guaranteed service level and clients should be made aware that they are effectively under a beta Services agreement.

Retrieved from: https://idaas.ng.bluemix.net/idaas/developer/
